"""UI-only test of the offline demo in system Chromium, not native Merlin HTTP."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, shutil
ROOT=Path(__file__).resolve().parents[1]
checks=[];errors=[];external=[]
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    page=b.new_page(viewport={'width':1440,'height':1080},device_scale_factor=1)
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:external.append(r.url) if r.url.startswith(('http://','https://')) else None)
    page.on('dialog',lambda d:d.accept())
    page.set_content((ROOT/'preview.html').read_text(), wait_until='load')
    page.wait_for_function('document.querySelector("#message").textContent.includes("Interactive demo")')
    assert page.locator('#previewNotice').is_visible();checks.append('Conspicuous offline-demo label')
    page.click('[data-tab="countries"]')
    assert page.locator('#countryList input').count()==249;checks.append('249 selectable country controls')
    page.fill('#countrySearch','Netherlands')
    assert page.locator('#countryList input').count()>=1;checks.append('Country name search')
    page.fill('#countrySearch','')
    page.screenshot(path=str(ROOT/'docs/preview-countries.png'),full_page=True)
    page.click('#clearCountries')
    assert not page.locator('#countryEnabled').is_checked()
    assert page.evaluate('window.MCG_DEMO_STATE.config.countries.length')==3
    checks.append('Clear selection disables only draft country policy, not saved policy')
    page.check('#countryEnabled');page.click('#apply')
    assert 'at least one' in page.inner_text('#message');checks.append('Empty allowlist activation rejected in UI')
    page.click('#resetDraft')
    page.click('[data-tab="ports"]');page.fill('#portValue','1000-2000');page.click('#addPort')
    assert page.locator('#portRows tr').count()==2;checks.append('Add port range')
    page.fill('#portValue','65536');page.click('#addPort')
    assert page.locator('#portRows tr').count()==2;checks.append('Out-of-range port rejected')
    page.click('#apply');page.wait_for_selector('#pendingBox:not(.hidden)')
    assert page.evaluate('window.MCG_DEMO_STATE.config.ports.length')==2
    page.click('#rollback');page.wait_for_function('window.MCG_DEMO_STATE.pending===null')
    assert page.evaluate('window.MCG_DEMO_STATE.config.ports.length')==1;checks.append('Demo candidate rollback restores previous configuration')
    page.click('[data-tab="tables"]');page.click('#readTables')
    page.wait_for_function('document.querySelector("#tablesText").textContent.includes("*raw")');checks.append('Demo table inspection')
    page.click('[data-tab="stats"]');page.fill('#connectionSearch','198.51.100.10')
    assert page.locator('#connectionRows tr').count()==1;checks.append('Connection filtering')
    page.fill('#connectionSearch','');page.screenshot(path=str(ROOT/'docs/preview-statistics.png'),full_page=True)
    page.click('[data-tab="updates"]')
    assert page.locator('#updateAutoCheck').is_checked() and page.locator('#updateAutoDownload').is_checked()
    assert page.locator('#updateInstall').is_disabled();checks.append('Update defaults: checks/downloads enabled, installation unavailable without a package')
    page.click('#updateCheck')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.staged!==null')
    page.wait_for_function('!document.querySelector("#updateInstall").disabled')
    assert 'No network' in page.inner_text('#updateMessage')
    checks.append('Demo commit change and automatic staging, without network access')
    page.screenshot(path=str(ROOT/'docs/preview-updates.png'),full_page=True)
    page.click('#updateInstall')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.installed_commit === "2".repeat(40)')
    page.wait_for_function('document.querySelector("#updateVersion").textContent.includes("0.3.1")')
    assert page.evaluate('window.MCG_DEMO_STATE.updates.staged===null')
    checks.append('Explicit update installation and staged-package reset in demo')
    page.click('#updateRollback')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.installed_commit === "1".repeat(40)')
    checks.append('Demo application rollback')
    page.uncheck('#updateAutoCheck')
    assert not page.locator('#updateAutoDownload').is_checked()
    page.click('#updateSave')
    page.wait_for_function('!window.MCG_DEMO_STATE.updates.settings.auto_check')
    checks.append('Automatic downloads cannot remain enabled when checks are disabled')
    page.fill('#updateInterval','6');page.check('#updateAutoCheck');page.click('#updateSave')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.settings.interval_hours===6 && window.MCG_DEMO_STATE.updates.settings.auto_check')
    checks.append('Custom GitHub interval saved without applying a firewall policy')
    page.uncheck('#updateEnabled');page.click('#updateSave')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.settings.enabled===false')
    page.wait_for_function('document.querySelector("#updateCheck").disabled')
    assert page.locator('#updateDownload').is_disabled() and page.locator('#updateInstall').is_disabled()
    assert not page.locator('#updateRollback').is_disabled()
    checks.append('Full GitHub disable blocks check/download/install controls but keeps rollback')
    page.check('#updateEnabled');page.uncheck('#updateAutoCheck');page.click('#updateSave')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.settings.enabled && !window.MCG_DEMO_STATE.updates.settings.auto_check')
    page.wait_for_function('!document.querySelector("#updateCheck").disabled')
    checks.append('Manual-only GitHub mode leaves explicit checks available')
    page.fill('#updateInterval','0');page.click('#updateSave')
    assert 'integer' in page.inner_text('#message');checks.append('Out-of-range GitHub interval rejected in browser')
    page.fill('#updateInterval','24');page.check('#updateAutoCheck');page.check('#updateAutoDownload');page.click('#updateSave')
    page.wait_for_function('window.MCG_DEMO_STATE.updates.settings.interval_hours===24')
    page.click('[data-tab="countries"]');page.fill('#countryInterval','6');page.uncheck('#countryAutoUpdate');page.click('#countryUpdateSave')
    page.wait_for_function('window.MCG_DEMO_STATE.country_updates.settings.interval_hours===6 && !window.MCG_DEMO_STATE.country_updates.settings.auto_update')
    assert not page.locator('#countryRefresh').is_disabled()
    checks.append('Country schedule is independent; manual refresh survives automatic disable')
    page.click('#countryRefresh')
    page.wait_for_function('document.querySelector("#countryUpdateMessage").textContent.includes("simulated")')
    checks.append('Manual selected-country refresh is wired to the demo action')
    page.fill('#countryInterval','24');page.check('#countryAutoUpdate');page.click('#countryUpdateSave')
    page.wait_for_function('window.MCG_DEMO_STATE.country_updates.settings.interval_hours===24')
    page.screenshot(path=str(ROOT/'docs/preview-countries.png'),full_page=True)
    page.click('[data-tab="stats"]')
    assert page.inner_text('#statCpu')!='—'
    assert page.locator('#interfaceRows tr').count()==2
    assert page.locator('#statsChart polyline').count()>0 and page.locator('#trafficChart polyline').count()==2
    checks.append('CPU, per-interface rates and two traffic chart series render')
    page.fill('#statsInterval','5');page.fill('#statsRetention','72');page.fill('#statsTopN','10');page.click('#statsSave')
    page.wait_for_function('window.MCG_DEMO_STATE.telemetry.settings.interval_minutes===5 && window.MCG_DEMO_STATE.telemetry.settings.retention_hours===72')
    checks.append('Statistics cadence and retention are saved independently')
    page.select_option('#statsGroup','protocols')
    assert page.locator('#rankingRows tr').count()==2
    checks.append('Protocol ranking groups observed connections')
    page.select_option('#connectionDirection','local')
    assert page.locator('#connectionRows tr').count()==0
    page.select_option('#connectionDirection','out');page.select_option('#connectionSort','bytes')
    assert page.locator('#connectionRows tr').count()==3
    assert '10.10.10.10' in page.locator('#connectionRows tr').first.inner_text()
    checks.append('Direction filter and byte-count ordering work')
    with page.expect_download() as download_info:page.click('#statsHistoryExport')
    downloaded=download_info.value
    assert 'time_utc' in Path(downloaded.path()).read_text(encoding='utf-8-sig')
    checks.append('History CSV export contains UTC time and interval fields')
    with page.expect_download() as download_info:page.click('#statsExport')
    report=json.loads(Path(download_info.value.path()).read_text())
    assert report['telemetry']['sample']['summary']['unique_local']==3
    checks.append('Statistics JSON export contains the displayed metrics')
    page.select_option('#statsGroup','local_ips');page.select_option('#connectionDirection','')
    page.screenshot(path=str(ROOT/'docs/preview-statistics.png'),full_page=True)
    page.click('[data-tab="updates"]');page.screenshot(path=str(ROOT/'docs/preview-updates.png'),full_page=True)
    for w in (1440,768,390):
        page.set_viewport_size({'width':w,'height':1000});page.click('[data-tab="countries"]')
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'),f'overflow at {w}'
        page.click('[data-tab="updates"]')
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'),f'updates overflow at {w}'
        page.click('[data-tab="stats"]')
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'),f'statistics overflow at {w}'
    checks.append('No country/update/statistics page-level horizontal overflow at 1440/768/390 px')
    assert not external;checks.append('No external network requests')
    assert not errors;checks.append('No JavaScript page errors')
    b.close()
result={'browser':'system Chromium; Playwright','passed':len(checks),'checks':checks,'errors':errors,'external_requests':external,'scope':'Self-contained offline preview only; not native Merlin WebUI, CGI or router kernel.'}
(ROOT/'docs/browser-test-results.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(result,indent=2))
